apiVersion: #<string>
kind: #<string>
metadata: #<Object>
  annotations: #<map[string]string>
  clusterName: #<string>
  creationTimestamp: #<string>
  deletionGracePeriodSeconds: #<integer>
  deletionTimestamp: #<string>
  finalizers: #<[]string>
  generateName: #<string>
  generation: #<integer>
  labels: #<map[string]string>
  managedFields: #<[]Object>
    apiVersion: #<string>
    fieldsType: #<string>
    fieldsV1: #<map[string]>
    manager: #<string>
    operation: #<string>
    subresource: #<string>
    time: #<string>
  name: #<string>
  namespace: #<string>
  ownerReferences: #<[]Object>
    apiVersion: #<string>
    blockOwnerDeletion: #<boolean>
    controller: #<boolean>
    kind: #<string>
    name: #<string>
    uid: #<string>
  resourceVersion: #<string>
  selfLink: #<string>
  uid: #<string>
spec: #<Object>
  behavior: #<Object>
    scaleDown: #<Object>
      policies: #<[]Object>
        periodSeconds: #<integer>
        type: #<string>
        value: #<integer>
      selectPolicy: #<string>
      stabilizationWindowSeconds: #<integer>
    scaleUp: #<Object>
      policies: #<[]Object>
        periodSeconds: #<integer>
        type: #<string>
        value: #<integer>
      selectPolicy: #<string>
      stabilizationWindowSeconds: #<integer>
  maxReplicas: #<integer>
  metrics: #<[]Object>
    containerResource: #<Object>
      container: #<string>
      name: #<string>
      target: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        type: #<string>
        value: #<string>
    external: #<Object>
      metric: #<Object>
        name: #<string>
        selector: #<Object>
          matchExpressions: #<[]Object>
            key: #<string>
            operator: #<string>
            values: #<[]string>
          matchLabels: #<map[string]string>
      target: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        type: #<string>
        value: #<string>
    object: #<Object>
      describedObject: #<Object>
        apiVersion: #<string>
        kind: #<string>
        name: #<string>
      metric: #<Object>
        name: #<string>
        selector: #<Object>
          matchExpressions: #<[]Object>
            key: #<string>
            operator: #<string>
            values: #<[]string>
          matchLabels: #<map[string]string>
      target: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        type: #<string>
        value: #<string>
    pods: #<Object>
      metric: #<Object>
        name: #<string>
        selector: #<Object>
          matchExpressions: #<[]Object>
            key: #<string>
            operator: #<string>
            values: #<[]string>
          matchLabels: #<map[string]string>
      target: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        type: #<string>
        value: #<string>
    resource: #<Object>
      name: #<string>
      target: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        type: #<string>
        value: #<string>
    type: #<string>
  minReplicas: #<integer>
  scaleTargetRef: #<Object>
    apiVersion: #<string>
    kind: #<string>
    name: #<string>
status: #<Object>
  conditions: #<[]Object>
    lastTransitionTime: #<string>
    message: #<string>
    reason: #<string>
    status: #<string>
    type: #<string>
  currentMetrics: #<[]Object>
    containerResource: #<Object>
      container: #<string>
      current: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        value: #<string>
      name: #<string>
    external: #<Object>
      current: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        value: #<string>
      metric: #<Object>
        name: #<string>
        selector: #<Object>
          matchExpressions: #<[]Object>
            key: #<string>
            operator: #<string>
            values: #<[]string>
          matchLabels: #<map[string]string>
    object: #<Object>
      current: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        value: #<string>
      describedObject: #<Object>
        apiVersion: #<string>
        kind: #<string>
        name: #<string>
      metric: #<Object>
        name: #<string>
        selector: #<Object>
          matchExpressions: #<[]Object>
            key: #<string>
            operator: #<string>
            values: #<[]string>
          matchLabels: #<map[string]string>
    pods: #<Object>
      current: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        value: #<string>
      metric: #<Object>
        name: #<string>
        selector: #<Object>
          matchExpressions: #<[]Object>
            key: #<string>
            operator: #<string>
            values: #<[]string>
          matchLabels: #<map[string]string>
    resource: #<Object>
      current: #<Object>
        averageUtilization: #<integer>
        averageValue: #<string>
        value: #<string>
      name: #<string>
    type: #<string>
  currentReplicas: #<integer>
  desiredReplicas: #<integer>
  lastScaleTime: #<string>
  observedGeneration: #<integer>
